### ISSUE TITLE
Move cursor to next line upon single line execution

### ISSUE THREAD

**Issue by matt035343** [matt035343/interactive-scala#8]

**Comment by xgdgsc** [comment]
Yes. It is very annoying to move back cursor from REPL.

**Comment by yelled1** [comment]
Let me add (this might be a bit out of scope but... this is related): 
If in visual code execution, then after execution visual mode should be cleared & the cursor should be on the next line. Rather than down on the REPL.
Very useful & fairly good, but really could use this change. 
In fact, I would even take it, if cursor can NEVER even get to the REPL, as all command can be sent from the editor.
Thank you,

This is how I jump between terminal & editor using "ctr-x o" a la emacs.
{ "key": "ctrl+x o", "command": "workbench.action.terminal.focus", "when": "editorTextFocus" },
{ "key": "ctrl+x o", "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus"},
Hope this helps or may be I can attempt a pull request (dangerous idea as I never programmed in ts)

**Comment by xgdgsc** [comment]
Also wondering whether `:require ` could be executed in editor.

**Comment by matt035343** [comment]
I will take a look at this very soon. Thanks for your input @yelled1.

@xgdgsc If you are asking for a feature for providing a list of files to be required, you are very welcome to open a new issue and I will take a look.

**Comment by yelled1** [comment]
Thank you for ur response:
This url might help you, as these are Macros written to shore up the old Python REPL, when the darn thing was Young & Restless.
https://github.com/Microsoft/vscode/issues/43822
"expandLineSelection",
"python.execSelectionInTerminal",
"cancelSelection"

**Comment by matt035343** [comment]
Moved @xgdgsc's request to issue #12.

The rest is fixed and will be released with the next update
